Tweaks:
  # Minimum ticks of interval between growing
  cooldownTicks: 5
  # Grow saplings when player sneaks
  growSaplings: 100
  # Grow crops when player sneaks
  growCrops: 100
  # Show bonemeal particles when appropriate. Not sure why you would turn this off, but eh
  showParticles: true
